CREATE TABLE T_DASHBOARD_ITEM_TYPES 
   (
    TYPE_ID VARCHAR2(100) NOT NULL ENABLE, 
	TITLE VARCHAR2(200), 
	DESCRIPTION VARCHAR2(1000), 
	ICON VARCHAR2(50) NOT NULL ENABLE, 
	DEFAULT_WIDTH NUMBER NOT NULL ENABLE, 
	DEFAULT_HEIGHT NUMBER NOT NULL ENABLE, 
	CONSTRAINT T_DASHBOARD_ITEM_TYPES_PK PRIMARY KEY (TYPE_ID) USING INDEX  ENABLE
   );

CREATE TABLE T_DASHBOARD_ITEMS 
   (
    ITEM_IDENT NUMBER GENERATED ALWAYS AS IDENTITY, 
	DASHBOARD_IDENT NUMBER NOT NULL ENABLE, 
	ITEM_TITLE VARCHAR2(200), 
	ITEM_WIDTH NUMBER NOT NULL ENABLE, 
	ITEM_HEIGHT NUMBER NOT NULL ENABLE, 
	ITEM_ORDER_NUMBER NUMBER, 
	TYPE_ID VARCHAR2(50) NOT NULL ENABLE, 
	ATTRIBUTE_01 VARCHAR2(4000 CHAR), 
	ATTRIBUTE_02 VARCHAR2(4000 CHAR), 
	ATTRIBUTE_03 VARCHAR2(4000 CHAR), 
	ATTRIBUTE_04 VARCHAR2(4000 CHAR), 
	ATTRIBUTE_05 VARCHAR2(4000 CHAR), 
    ATTRIBUTE_01_C CLOB, 
    CONSTRAINT T_DASHBOARD_ITEMS_PK PRIMARY KEY (ITEM_IDENT) USING INDEX  ENABLE
   );

ALTER TABLE T_DASHBOARD_ITEMS ADD CONSTRAINT T_DASHBOARD_ITEMS_CON FOREIGN KEY (TYPE_ID) REFERENCES T_DASHBOARD_ITEM_TYPES (TYPE_ID) ENABLE;

